import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Clock from "../components/Clock";
import Weather from "../components/Weather";
import Quotes from "../components/Quotes";
import Goal from "../components/Goal";
import Settings from "../components/Settings";
import Greeting from "../components/Greeting";
import { ToggleContext } from "../components/ToggleContext";

export default function Home() {
  const [toggled, setToggled] = useState<boolean>(true);
  const [toggled2, setToggled2] = useState<boolean>(true);
  const [toggled3, setToggled3] = useState<boolean>(true);
  const [toggled4, setToggled4] = useState<boolean>(true);
  const [toggled5, setToggled5] = useState<boolean>(true);

  const [imageData, setImageData] = useState<any>();

  useEffect(() => {
    const fetchImage = async () => {
      const url = `http://localhost:3000/api/background`;
      const result = await fetch(url, {
        method: "GET",
        mode: "cors",
        headers: {
          "Content-Type": "application/json",
        },
      });
      const ImageEvent = await result.json();
      setImageData(ImageEvent.result[1].urls.full);
      //console.log(ImageEvent);
    };
    fetchImage();
  }, []);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToggleContext.Provider
        value={{
          toggled,
          toggled2,
          toggled3,
          toggled4,
          toggled5,
          setToggled,
          setToggled2,
          setToggled3,
          setToggled4,
          setToggled5,
        }}
      >
        <div
          style={{ backgroundImage: `url(${imageData})` }}
          className="text-white pt-4 px-10 font-poppins h-screen w-screen bg-cover bg-center outline-none"
        >
          <Settings />
          <div className="flex justify-between pt-20">
            <h1 className="text-3xl">
              <Greeting />
            </h1>
            <Clock />
          </div>
          <div className="mt-10 px-1 flex justify-between">
            <Weather />
            <Goal />
          </div>
          <div className="w-screen bottom-0 fixed">
            <Quotes />
          </div>
        </div>
      </ToggleContext.Provider>
    </div>
  );
}
